-- Create inc_tbl table for incoming form data
-- MySQL Database

CREATE DATABASE IF NOT EXISTS inventory_system;
USE inventory_system;

-- Incoming table for form data
CREATE TABLE IF NOT EXISTS inc_tbl (
  id INT AUTO_INCREMENT PRIMARY KEY,
  SUPPLIER VARCHAR(100),
  DATE VARCHAR(8), -- YYYYMMDD format
  REF VARCHAR(50),
  DINFLAG VARCHAR(1) DEFAULT 'D',
  BENZ VARCHAR(16),
  BENZ2 VARCHAR(16),
  BENZ3 VARCHAR(16),
  BRAND VARCHAR(50),
  ALTNO VARCHAR(20),
  ALTNO2 VARCHAR(20),
  `DESC` VARCHAR(100), -- Description
  APPL VARCHAR(100), -- Application
  COLORCODE VARCHAR(20),
  REMARKS TEXT,
  COST DECIMAL(10,2) DEFAULT 0,
  SELL DECIMAL(10,2) DEFAULT 0,
  QTY INT DEFAULT 0,
  CURRENCY VARCHAR(10) DEFAULT 'PHP',
  FCAMOUNT DECIMAL(10,2) DEFAULT 0,
  CONVERSION DECIMAL(10,4) DEFAULT 1,
  LOCATION VARCHAR(50),
  factor DECIMAL(10,4) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_benz (BENZ),
  INDEX idx_brand (BRAND),
  INDEX idx_date (DATE),
  INDEX idx_supplier (SUPPLIER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
